List mintable collections on assets page
AstarNetwork/ink-redible-nft pull request #23
Opened 2023-06-11 13:49 UTC by bobo-k2

Display mintable collections from Polkaverse.
I merged the previous PR because I had some fixes and this new feature in different branch, so let's use this PR to resolve bugs.

Ignore files in modules folder since they are auto-generated

<img width="1310" alt="image" src="https://github.com/AstarNetwork/ink-redible-nft/assets/8452361/2daebea8-6c2c-431a-9361-27788145059b">

2023-06-12 02:44 UTC, impelcrypto requested changes

2023-06-12 02:44 UTC, impelcrypto commented on src/hooks/useCollectionInfo.ts
> +  const fetchInfo = async (query: string) => {
```suggestion
  const fetchInfo = async (query: string): Promise<void> => {
```

2023-06-12 11:06 UTC, bobo-k2 commented on src/hooks/useCollectionInfo.ts
> +  const fetchInfo = async (query: string) => {
Fixed here https://github.com/AstarNetwork/ink-redible-nft/pull/23/commits/c4cf1b8223750de0f86f6447099059fcf5324c42

2023-06-12 12:29 UTC, impelcrypto approved these changes

2023-06-12 13:47 UTC, sirius651 approved these changes

2023-06-12 15:48 UTC, Kahonnohak commented
Styling request please, or please assign someone to help you.
1)  responsive behaviour on the Asset page
- Its just quite messy. I wish to achieve something very simple standard responsive card layout.
https://codepen.io/Katiae/pen/zwjmbW
I'm not going to be fussy but would be better to keep the padding the same.

2) button aligned
- Please keep the button left-aligned, and the space between buttons is 16px.
<img width="719" alt="Screenshot 2023-06-12 at 16 44 54" src="https://github.com/AstarNetwork/ink-redible-nft/assets/77480847/92b11dbe-22b7-4063-bb71-9c9c444ad5e3">
<img width="684" alt="Screenshot 2023-06-12 at 16 46 28" src="https://github.com/AstarNetwork/ink-redible-nft/assets/77480847/e057b1ec-b3b3-41d7-ab81-cb9d8eaa8000">

2023-06-13 13:32 UTC, Kahonnohak commented
Great work @bobo-k2 

I confirm all functions works great!

Those are not very critical but good be taken care of. Whenever you have time.

- Specifics default rather than Attribute
- Token ID - Extrinsic ID
- Github - ink!redible NFT repo
- Wallet modal update (if possible or if any volunteers...)

@impelcrypto sorry to mention but do you think you could update the wallet modal...?

2023-06-15 07:07 UTC, Kahonnohak approved these changes
Great work!

2023-06-15 07:59 UTC, merged